#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidRPG.Resource", IsApplication=true)]

namespace AndroidRPG
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int DownArrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EnterButton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LeftArrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MenuButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RightArrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int UpArrow = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int DownButton = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int EnterButton = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int LeftButton = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int MenuButton = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int PlayButton = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int RightButton = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int UpButton = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int button1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int space1 = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int space2 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040003
			public const int AgilityMultiplier = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int EnduranceMultiplier = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int IntelligenceMultiplier = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int NumberOfGenders = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int NumberOfStats = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int PerceptionMultiplier = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int SpecialBase = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int SpecialRollVariance = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int StatRollVariance = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int StrengthMultiplier = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int VitalityMultiplier = 2130968583;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PlayLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int AgilityStat = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int EnduranceStat = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int GenderList = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int IntelligenceStat = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int PerceptionStat = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int PlayButton = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int StatsList = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int StrengthStat = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int VitalityStat = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
